language: r

r:
  - release

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
      apt:
        packages:
        - littler
    - os: osx
      osx_image: xcode10

before_script:
  - Rscript --version
  - R --version

script:
  - cd somatic
  - Rscript clinCNV.R --normal ../samples/coverages_normal.cov --bed ../samples/bed_file.bed folderWithScript $PWD
  - ls ./result/
