language: r

r:
  - release

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y littler ; fi

before_script:
  - Rscript --version
  - R --version

script:
  - cd somatic
  - Rscript --normal normal.cov --out ../samples/ --bed ../samples/bed_file.bed folderWithScript $PWD
  - diff ../samples/normal.cov ../samples/coverages_normal.cov
